### PR TITLE
Fixed Chunker Evaluation Iss222 and ChunkAnnotator Init Bug Iss221 (new)

### PR DESCRIPTION
**Pull request by qiangning**
This time I had synced with upstream before making changes. I found out the reason why I couldn't compile the merged branch last time: Intellij suggested me update maven index after the merge but I didn't see it :-(

What's the standard thing I need to do after merging with a newer version? mvn clean+mvn compile?

### CODE REVIEW

**Comment by qiangning** [comment]
It fails again. It seems not to be that my fork was old. Let's see what the error is tomorrow.

**Comment by qiangning** [comment]
Hey Daniel, I suspect that it's an issue within our `IllinoisCogComp:master`. Just now I cloned a new copy of `IllinoisCogComp:master` and ran `mvn compile`.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project illinois-core-utilities: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :illinois-core-utilities
```
which is exactly what I saw previously. I think this indicates that there is something wrong with our `IllinoisCogComp:master`. Do you think so or did I do something wrong?

**Comment by mssammon** [comment]
@qiangning this is a java version issue.  You need to make sure that both your machine and your IDE are set to use version 1.8.  Machine: see 'java' on the wiki: https://wiki.illinois.edu/wiki/pages/viewpage.action?pageId=372375701
For the Intellij settings, see the heading 'Intellij' on the same page.

**Comment by qiangning** [comment]
I changed my java to 1.8 and now my fork can run properly from my side. Will the check perform automatically or do I have to create a new PR?

**Comment by mssammon** [comment]
should rebuild automatically when you push... looks like there is some kind of fundamental problem, though, as the build fails immediately.

**Comment by qiangning** [comment]
Hey @danyaljj , looks like semaphore is happy with this. What does the cross before cogcomp-nlp mean?

**Comment by danyaljj** [comment]
Ignore that (it is Jenkins, another CI, which is not working properly yet).  
Only Semaphore mattes for now.

**Pull request merged**
