### PR TITLE
Fix: serialization shouldn't fail upon view being null.

### PR DESCRIPTION
**Pull request by danyaljj**
Addendum on #91 
Previous changes in #91 were not quite correct. Fixed the issue and added the case to the UTest. 

@christos-c @mssammon  For whoever has time

### CODE REVIEW

**Comment by mssammon** [comment]
Is there a test that verifies the deserialization is correct when a null view is present?

**Comment by danyaljj** [comment]
I added the scenario to the test as well. See the changes.

**Comment by danyaljj** [comment]
Any positive/negative opinions on this?

**Comment by christos-c** [comment]
Can merge but hard to deploy.

**Pull request merged**
