### PR TITLE
Synchronized BrownCluster init

### PR DESCRIPTION
**Pull request by cowchipkid**
BrownCluster initialization was not sychronized, resulting in race conditions during startup when lazyLoading enabled.

### CODE REVIEW

**Comment by cowchipkid** [comment]
This did not build correctly on my machine, the POS view was not available when expected during the edu.illinois.cs.cogcomp.curator.CuratorFactoryTest.testGetIndividualTextAnnotationViews. I don't see how this could be the result of the simple change I made, but I am looking into this further.

**Comment by cowchipkid** [comment]
Perhaps it's connectivity issue, mvn build fails on master same as it does on my fork when I run at home.

**Comment by mssammon** [comment]
the Curator POS is running properly, and does not appear to be involved in the CI failure. 
From home, the failure will happen because the test is trying to access the curator across the UIUC/CS firewall.  You should check out your branch on one of our servers and run remotely to verify it's working properly.

This failure looks like a time-out while downloading dependencies -- I'd hoped we were past that particular problem.  I'll force a rebuild and see if the problem remains.

**Comment by danyaljj** [comment]
Looks good to me. One comment befor we merge; is there a way to verify that indeed it fixes the issue? Like maybe a timing experiment?

**Comment by cowchipkid** [comment]
I am reprocessing our repository of 100M documents, massively multi-threaded. Works there. That's how I have found all these race conditions.

**Pull request merged**
