### PR TITLE
Added a conll reader.

### PR DESCRIPTION
**Pull request by mayhewsw**
This reads conll 2002/2003 NER data into TextAnnotation.

At some point, if we want to convert illinois-ner to use TextAnnotations, this may be useful.

NOTE: this only reads BIO.

### CODE REVIEW

**Comment by danyaljj** [comment]
Missing license headers: `mvn license:format`

**Comment by mssammon** [comment]
@mayhewsw , is this a Work In Progress or is it complete now?

**Comment by mayhewsw** [comment]
Sorry... it was a WIP overnight, but is complete now.

**Comment by danyaljj** [comment]
All look good; merging.

**Pull request merged**
