### PR TITLE
More link fixes, and documentation updated.

### PR DESCRIPTION
**Pull request by mayhewsw**
Just changing the NER readme to be more accurate.

### CODE REVIEW

**Comment by christos-c** [comment]
I think we should move the maven part higher up in the readme file, and also add the repository part of the pom file.

**Comment by mayhewsw** [comment]
I agree about maven. Not sure I understand about "repository part of the pom file"? You mean add the <repository>... cogcomp.../m2repo</repository> thing?

One outstanding problem in this readme is that it is confused about the audience: is it intended for people cloning from github, or downloading from the website?

**Comment by christos-c** [comment]
Yes, I meant adding the `<repositories>` in the pom

I agree that we need to standardise the way we present usage; I think the order should be Maven, then zip download, then source forked/cloned.

**Comment by danyaljj** [comment]
Wow you can assign multiple people to PRs now! 😄

**Comment by danyaljj** [comment]
@christos-c maybe we address ur suggestion in another PR? (and for all the sub-projects)

**Comment by christos-c** [comment]
Ok, but do you mind starting a WIP PR then? I can merge this one after.

**Comment by danyaljj** [comment]
I will create an issue to remember it! 😆

**Pull request merged**
