### PR TITLE
moving primitive vectors to core utils.

### PR DESCRIPTION
**Pull request by danyaljj**
This moves the primitive vectors from lbjava (https://github.com/IllinoisCogComp/illinois-sl/issues/19#issuecomment-228820810). **No change in functionality; just moving files.** 

Note: This does NOT move datastructures related to feature vectors and lexicons (although it is a feasible options, it needs a bigger-scale move). 

Upon merging, I will create another PR, removing things in lbjava that are moved by this PR and add core-utils as dependency of lbjava-core.

### CODE REVIEW

**Comment by christos-c** [comment]
What's the second PR going to do exactly? I thought you moved these in core utilities in this PR

**Comment by danyaljj** [comment]
Typos. Corrected: 
>  Upon merging, I will create another PR, removing things in lbjava that are moved by this PR and add core-utils as dependency of lbjava-core.

**Comment by christos-c** [comment]
Ok, good. Going to merge now since this a slightly inconsequential change.

**Comment by christos-c** [comment]
@danyaljj @shyamupa at some point we'll have to unify SL's and LBJava's feature vector structures.

**Comment by danyaljj** [comment]
Good point. It can be a mother package (core-classifier-utils) which contains all the primitives for classifiers and feature vectors etc. It needs a bit of coordination across our learning packages.

**Pull request merged**
