### PR TITLE
reorganize and document srl feature extractors, and create shells for missing tests

### PR DESCRIPTION
**Pull request by mssammon**
removed duplicate feature extractors/reorganized accordingly. Added keywords and documentation. Renamed tests where appropriate.

### CODE REVIEW

**Comment by pauljv92** [comment]
@mssammon The changes look good, but some of the tests could use some additional comments. Would I be able to add to this branch? Any idea why semaphoreci might be failing?

**Comment by mssammon** [comment]
Since this change set is already large, please go ahead and merge if you are able to build locally. Then, if you want to add comments, you can go ahead and create a new PR for them...

**Comment by pauljv92** [comment]
There are test failures in curator which is causing the testing to fail half-way. But also in edison there seem to be some failed tests. Both compile fine. -  testParsePhraseCharniak(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest):
testParsePhraseStanford(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest):
testParsePhraseGold(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest):
testBinaryExample(edu.illinois.cs.cogcomp.edison.utilities.TestWriteSVMLightFormat)
testMulticlassExample(edu.illinois.cs.cogcomp.edison.utilities.TestWriteSVMLightFormat): 

@mssammon what might be the problem here?

**Comment by mssammon** [comment]
I checked this fork out on a new machine and installed it first time, no problem.

**Comment by mssammon** [comment]
@danyaljj  can I get a second opinion here?

**Comment by danyaljj** [comment]
A common-resources problem (again): 
```
[ERROR] Failed to execute goal on project illinois-edison: Could not resolve dependencies for project edu.illinois.cs.cogcomp:illinois-edison:jar:3.0.42: Could not transfer artifact edu.illinois.cs.cogcomp:illinois-common-resources:jar:1.3 from/to CogcompSoftware (http://cogcomp.cs.illinois.edu/m2repo/): GET request of: edu/illinois/cs/cogcomp/illinois-common-resources/1.3/illinois-common-resources-1.3.jar from CogcompSoftware failed: Premature end of Content-Length delimited message body (expected: 457574985; received: 228541024 -> [Help 1]
[ERROR]
```

**Comment by mssammon** [comment]
this is a problem you see in your local build? (which machine?)
-- this should not change from one build to the next...

**Comment by danyaljj** [comment]
Nope I was just checking Semaphore log: 

screen shot 2016-05-25 at 8 42 34 pm

**Comment by mssammon** [comment]
semaphore is now reliably failing on downloading illinois-common-resources. I'm increasingly in tune with your goal of using minio.

**Pull request merged**
