### PR TITLE
New SRL in Edison

### PR DESCRIPTION
**Pull request by xinbowu2**

### CODE REVIEW

**Comment by xinbowu2** [comment]
@mssammon @christos-c @danyaljj 

Can anyone help me check what wrong with this?

**Comment by xinbowu2** [comment]
Ok, I tried Maven install for Edison. It shows one test failure in testGazetteerFeatures, which expects null (no gazetteer folder). The possible reason could be I added a Gazzetteer folder and a currency.gz inside it, because SRL needs it. Do we need to change testGazetteerFeatures?

**Comment by mssammon** [comment]
you should remove the gazetteer folder: this dependency must come from illinois-common-resources.

**Comment by xinbowu2** [comment]
Should I add the entire Illinois-common-resources?

2016-05-21 10:46 GMT+08:00 Mark Sammons <notifications@github.com>:

**Pull request closed without merging**
