### PR TITLE
Change the default parameters

### PR DESCRIPTION
**Pull request by yxd126**
The old default value of learning rate and thickness is 0.1 and 20. Now change to 0.05 and 30.

### CODE REVIEW

**Comment by danyaljj** [comment]
@yxd126 do we have enough reason to believe that this change is important/helpful? If so, it's always good to mention them explicitly in the PRs.

**Comment by yxd126** [comment]
@danyaljj Tom has made a table to show different parameters' performance on different data sets. 0.05 and 30 has the highest sum of all the results.  I have attached the table.
[NERParameterSweep.xlsx](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/files/473292/NERParameterSweep.xlsx)

**Comment by danyaljj** [comment]
@cowchipkid are there any further experiments need to be done for this? 
At least the model should be retrained with these params; right?

**Comment by mssammon** [comment]
@yxd126 did your results come from retraining and evaluating the NER on the relevant data set(s)? Ideally run on all 4 but you should train/evaluate at least CoNLL and OntoNotes.

**Comment by cowchipkid** [comment]
I think this change set will have no effect, since from what I see the java files generated from the lbjava have not been recompiled. Also, the parameters for the level 1 tagger have not been changed.@yxd126 I think I should make these changes since I have already done some of the work, and know what is required. I will make the necessary changes on my fork, and check them in along with the useless ERE readers I have been working on. I will recompile the models and send the results around as well.

**Comment by mssammon** [comment]
@danyaljj @bhargav semaphore indicates build failed due to invalid target release 1.8 -- is this a setting that I need to change?

**Comment by danyaljj** [comment]
Not sure what build status you're talking about ....

**Pull request merged**
