### PR TITLE
Fixed H2 DBHelper error

### PR DESCRIPTION
**Pull request by christos-c**
New version of H2 will create a `.mv.db` file instead of the old `.h2.db`

### CODE REVIEW

**Comment by danyaljj** [comment]
I'm no expert at this, but seem like [the correct behavior on h2 version](http://stackoverflow.com/a/27100675).

**Comment by christos-c** [comment]
Not sure what you mean. Right now I'm catching both cases, previously only one was caught. I don't want to remove the old one because it's unclear whether it's going to be abandoned in the future.

**Comment by christos-c** [comment]
Btw, testing still fails because of the resources size

**Comment by danyaljj** [comment]
The link says it's either `.h2` **or** `.m2` (while your condition is **and**). As I mentioned I have not used this; not sure how reliable that StackOverFlow link is.... 
Resources: I'm bugging @mssammon about testing [Minio](minio.io) as a datastore, still waiting for engrit ...

**Comment by christos-c** [comment]
I'm doing an & on the negations, which means I'm either failing CS 101 or you are :smile:

**Comment by danyaljj** [comment]
Will merge&deploy tonight.

**Pull request merged**
