### PR TITLE
adding tag information for chunker and NERAnnotator

### PR DESCRIPTION
**Pull request by tofuwen**
issue #237

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks @tofuwen! Why don't we get the tags automatically?

**Comment by tofuwen** [comment]
What do you mean by "automatically"?
The implementation for Chunker and Ner is almost the same for POS.
Do you mean I should add the method in tagger class, just as in POS?

**Comment by danyaljj** [comment]
I'm referring to extracting the tag set, rather than listing them statically in the code.

**Comment by mssammon** [comment]
BTW @danyaljj the listing of tags appears to be in the Test classes, as a way to compare against the automatic retrieval of tags.

**Comment by danyaljj** [comment]
@mssammon @tofuwen Ah I see. My bad ....

**Comment by tofuwen** [comment]
As @bhargav  suggested here: 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/pull/235
Which way of implementation is preferred?
I can change all the three implementation according to the suggestion.

@mssammon Are you suggesting that I shouldn't change the constructor, instead of creating a new one?

The issue for the current constructor implementation is that:
If you ever call the default constructor (like "new ChunkerAnnotator()"), it will throw an exception.

And in the test, there is no call to the ChunkerAnnotator. 

Is this a bug, or it's intentionally?

**Comment by mssammon** [comment]
There should be a test for ChunkerAnnotator. 
The default constructor should call another constructor with a default ResourceManager (create from Configurator) and lazyInit flag; this constructor should call super(). This last constructor will use new ChunkerConfigurator().getConfig( nonDefaultConfig) to ensure that all the fields are set wherever it is called from.

**Comment by mssammon** [comment]
Regarding which implementation for getting the tags, from my perspective any of them is fine so long as it has the desired behavior.

**Comment by bhargav** [comment]
@tofuwen In my opinion, you should use either of the two methods that use `.getLabelLexicon()` instead of the `.scores()` on a dummy example. The scores method would need to populate all features for the dummy token/word. 

If the classifier is trained, the LabelLexicon should be populated with all labels that are encountered during training. The .`scores()` method eventually ends up getting all labels from this lexicon and assigning scores corresponding to each label. So directly getting the tagset from the Label Lexicon would be better.

**Comment by tofuwen** [comment]
@bhargav Thanks! I will change it.

**Comment by danyaljj** [comment]
Merge call with Mark.

**Pull request merged**
