### PR TITLE
first version of the webserver

### PR DESCRIPTION
**Pull request by danyaljj**
Added a very simple webserver with [Spark Framework](http://sparkjava.com/). 
In the current form, you send a text, and it gives you the tokenized version: 

screen shot 2016-12-14 at 10 36 21 am

Update: 
Now it reads the view names and adds them one by one. 

An instance is running on austen:
http://austen.cs.illinois.edu:8080/annotate?text=%22This%20is%20a%20sample%20sentence.%20I%27m%20happy.%22&views=POS,NER_CONLL

And the result of making post request with Chrome Postman: 

screen shot 2016-12-14 at 3 29 00 pm

Partially responding to #307

### CODE REVIEW

**Comment by danyaljj** [comment]
Updated.
 - arbitrary views is possible now, for the ones included in the pipeline. 
 - implemented the post request.

**Comment by bhargav** [comment]
LGTM. Minor things for future:
- [ ] We should mention in the documentation that there is a light-weight REST API server available. 
- [ ] Move the print statements to use a logger instance.
- [ ] Add an API go get the names/information about views that the pipeline instance can populate. (This can be an extension in the future when we define the behavior properly)

Let me know if you want to address them in this PR or for later. I'll open an issue for tracking it if required.

**Comment by danyaljj** [comment]
All good suggestions! Address them in future PRs?

**Comment by danyaljj** [comment]
Merging and creating issue to address the suggestions.

**Pull request merged**
